check_columns:
  expected_cols:
    - 'item_sku'
    - 'item_price' 
    - 'release_date'
    - 'date_created'
    - 'date_updated' 
    - 'active'

check_unique:
  cols:
    - 'item_sku'

clean_date_formats:
  date_cols:
    - 'release_date'
    - 'date_created'
    - 'date_updated' 

check_ranges:
  column_ranges:
    'item_price': [0, 100]
  drop: false
  
rename_columns:
  cols: 
    'release_date': 'item_release_date'
    'date_created': 'item_creation_date'
    'date_updated': 'item_updated_date' 
    'active': 'item_active'

